version: '3'
services:
  app:
    build: .
    container_name: app_codeflix
    entrypoint: 'dockerize -wait tcp://db_codeflix:5432 -timeout 40s ./.docker/entrypoint.sh'
    volumes:
      - '.:/var/www'
    networks:
      - app-network
    depends_on:
      - db
      - redis

  nginx:
    build: .docker/nginx
    container_name: nginx_codeflix
    restart: always
    tty: true
    ports:
      - '8000:80'
    volumes:
      - '.:/var/www'
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: 'postgres:12.1'
    container_name: db_codeflix
    restart: unless-stopped
    tty: true
    ports:
      - '15432:5432'
    environment:
      #      POSTGRES_DB: codeflix
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - './.docker/db:/var/lib/postgresql/data'
      - './.docker/postgres:/docker-entrypoint-initdb.d'
    networks:
      - app-network
  redis:
    image: 'redis:alpine'
    expose:
      - 6379
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
